import { Toaster } from 'sonner'
import '@/shared/styles/global.css'
import type { Metadata } from 'next'
import { cn } from '@/shadcn/lib/utils'
import { Navbar } from '@/shared/components/Navbar'
import { Inter as FontSans } from 'next/font/google'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className="dark"
      suppressHydrationWarning
    >
      <body className={cn('min-h-screen bg-background font-sans antialiased overflow-x-hidden', fontSans.variable)}>
        <Navbar />

        {children}

        <Toaster
          duration={4000}
          visibleToasts={1}
          position="top-right"
        />
      </body>
    </html>
  )
}
